version: '2'
services:
  db:
    image: postgres
  coworking:
    image: efforia/mezzanine
    command: deploy/entrypoint.sh
    working_dir: /app 
    volumes:
      - .:/app/
    links:
      - db
    depends_on:
      - db
  proxy:
    image: nginx
    volumes:
      - .:/coworking/
      - ./deploy/:/etc/nginx/conf.d/
      - ./deploy/keys:/etc/nginx/keys/
    ports:
      - "80:80"
      - "443:443"
    links:
      - coworking
    depends_on:
      - coworking
