version: '2'
services:
  db:
    image: postgres
    external_links: 
      - db:postgres
  web:
    image: efforia/mezzanine
    command: bash -c "python manage.py collectstatic --noinput && python manage.py migrate --settings=\"coworking.production\" && gunicorn coworking.wsgi -b 0.0.0.0:8000"
    working_dir: /app 
    volumes:
      - .:/app/
    ports:
      - "8000"
    links:
      - db
    depends_on:
      - db
  proxy:
    image: nginx
    volumes:
      - .:/coworking/
      - ./deploy/:/etc/nginx/conf.d/
      - ./deploy/keys:/etc/nginx/keys/
    ports:
      - "80:80"
    links:
      - web
    depends_on:
      - web
