# Postgres image with db label and efforia labeled bridge network
# docker network create --driver bridge efforia
# docker run -d -p 5432:5432 --name db --net=efforia postgres
version: '2'
services:
  coworking:
    image: efforia/mezzanine
    command: deploy/entrypoint.sh
    working_dir: /app 
    container_name: coworking
    network_mode: "efforia"
    restart: always
    volumes:
      - ..:/app/
    external_links:
      - db:postgres
